language: csharp
solution: CsvAndXmlConverter.sln
install:
  - nuget restore CsvAndXmlConverter.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release CsvAndXmlConverter.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./CsvAndXmlConverterTests/bin/Release/CsvAndXmlConverterTests.dll